import { ExperienceItemProps } from "@/app/(pages)/experience/components/ExperienceItem";

export const InternExperience: ExperienceItemProps[] = [
    {
        title: "MNC Lab Intern",
        subtitle: "Mobile Network & Communication Lab, Korea University",
        date: "2023.12 - 2024.12",
        descriptions: [
            "I conducted research and development on 5G network systems using open-source platforms.",
            "Analyzed and customized OpenAirInterface (OAI) to meet specific research goals, and containerized core functionalities using Docker.",
            "Set up and tested a virtualized environment on Ubuntu using multiple containers, performed network integration testing, and resolved errors through in-depth troubleshooting.",
            "Studied 5G architecture and protocols in depth.",
            "Separated OAI modules into independent Docker images for modular testing.",
            "Built and deployed the environment in Ubuntu VM, ensuring seamless container networking.",
            "Identified and resolved critical network and deployment issues during integration."
        ],
        tags: ["5G", "Network", "Docker", "Ubuntu", "SDN"]
    }
]

export const GroupExperience: ExperienceItemProps[] = [
    {
        title: "KAIROS - Officer",
        subtitle: "LLM Club, Korea University",
        date: "2023.12 - present",
        descriptions: [
            "Operated weekly LLM lectures as a core member.",
            "Led material development on foundational LLM, web chatbot, RAG, finetuning, and agents.",
            "Developed generative AI-based services:",
            "🐱 Cat Companion App: Customizable AI pet with React-based frontend and LLM integration.",
            "💬 Health Management Chatbot: Full-stack service with OpenAI API, RAG, and finetuning.",
            "🎞️ AI Video Narration Generator: Multi-modal AI project generating narration from video.",
            "Organized and led Python study sessions."
        ],        
        tags: ["LLM", "Generative AI", "Agent"]
    },
    {
        title: "HANDS - Member",
        subtitle: "Hardware & Software Club, Korea University",
        date: "2022.03 - 2023.08",
        descriptions: [
            "Participated in various seminars on Python, deep learning, and software development.",
            "Developed a Flutter-based mobile application for schedule management and habit tracking with data analysis features.",
            "Led a deep learning project focused on detecting fake voices generated by generative AI models.",
            "Utilized PyTorch, MLP models, and Hugging Face tools to classify and detect synthetic audio."
        ],
        tags: ["Flutter", "Deep Learning", "PyTorch", "Hugging Face"]
    }
]

export const EducationExperience: ExperienceItemProps[] = [
    {
        title: "Advanced Algorithm Intensive Course",
        subtitle: "Samsung SDS",
        date: "2024.02",
        descriptions: [
            "Completed an intensive algorithm course hosted by Samsung SDS.",
            "Learned advanced problem-solving techniques and algorithm design strategies.",
            "Practiced a wide range of algorithm topics including dynamic programming, greedy algorithms, graph theory, and data structures.",
            "Improved problem-solving speed and accuracy through hands-on coding exercises and mock tests."
        ],
        tags: ["Algorithm", "Problem Solving", "Data Structure"]
    },
    {
        title: "Advanced AI Training Program",
        subtitle: "HD Hyundai",
        date: "2024.09 - 2024.12",
        descriptions: [
            "Completed an intensive AI training program hosted by HD Hyundai, focusing on advanced real-world applications.",
            "Studied key topics such as time series data analysis, natural language processing (NLP), and large language models (LLMs).",
            "Explored deep learning-based approaches for forecasting and anomaly detection in time series data.",
            "Built NLP pipelines and experimented with transformer models for tasks like text classification and summarization.",
            "Participated in hands-on projects that integrated both time series analytics and LLM-based solutions."
        ],
        tags: ["AI", "Time Series", "LLM", "NLP", "Deep Learning"]
    } 
]

